"""Vendor the blog's web fonts locally so no visitor's browser ever contacts
Google Fonts.

Google Fonts serves its stylesheet from fonts.googleapis.com and the font files
from fonts.gstatic.com, so every page view pings Google. This script downloads
the exact fonts the template uses into static/fonts/ and writes a self-contained
static/fonts.css that references them locally. The template then loads that one
stylesheet from our own domain instead of Google.

Run once (and re-run only if the font set in FONTS_CSS_URL changes):

    python3 fetch_fonts.py

The downloaded .woff2 files and the generated fonts.css are committed to the
repo (they're part of the theme, like static/dompurify.min.js), so a normal
build/deploy needs no network access for fonts.

Scope: only the 'latin' and 'latin-ext' unicode-range subsets are kept.
latin-ext covers German umlauts and essentially all Western/Central European
accents, which is everything this blog writes. Cyrillic/Greek/Vietnamese
subsets are dropped; a stray character in those scripts simply falls back to a
system font. All three families (Plus Jakarta Sans, Source Serif 4, Space Mono)
are SIL Open Font License, which permits self-hosting and redistribution.
"""

import os
import re
import sys
import urllib.request

# Output locations live in the engine's theme directory (see paths.py); the
# vendored fonts are tracked engine dependencies, not site content.
from paths import FONTS_DIR, FONTS_CSS as OUTPUT_CSS

# The exact Google Fonts request the template used. If you change which fonts
# or weights the blog uses, update this URL and re-run.
FONTS_CSS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Plus+Jakarta+Sans:wght@400;600;700&"
    "family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;1,8..60,400&"
    "family=Space+Mono&display=swap"
)

# unicode-range subsets to keep. latin-ext already covers German + Western/
# Central European accents; the rest are unnecessary for this blog.
KEEP_SUBSETS = {"latin", "latin-ext"}

# A modern-browser UA so Google serves woff2 (the smallest, widely-supported
# format) rather than older ttf/eot.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0 Safari/537.36")


def _fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = resp.read()
    return data if binary else data.decode("utf-8")


def _slug(family):
    return re.sub(r"[^a-z0-9]+", "-", family.lower()).strip("-")


def main():
    print(f"⬇️  Fetching font stylesheet from Google...")
    css = _fetch(FONTS_CSS_URL)

    # Google's CSS is a sequence of "/* subset */\n@font-face { ... }" pairs.
    # Split on the subset comment so each block is tagged with its subset name.
    parts = re.split(r"/\*\s*([a-z0-9-]+)\s*\*/", css)
    # parts = ['', subset1, block1, subset2, block2, ...]
    blocks = list(zip(parts[1::2], parts[2::2]))

    os.makedirs(FONTS_DIR, exist_ok=True)
    out_blocks = []
    downloaded = {}
    kept = 0

    for subset, block in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        m_fam = re.search(r"font-family:\s*'([^']+)'", block)
        m_wght = re.search(r"font-weight:\s*(\d+)", block)
        m_style = re.search(r"font-style:\s*(\w+)", block)
        m_url = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not (m_fam and m_url):
            continue
        family = m_fam.group(1)
        weight = m_wght.group(1) if m_wght else "400"
        style = m_style.group(1) if m_style else "normal"

        fname = f"{_slug(family)}-{weight}-{style}-{subset}.woff2"
        dest = os.path.join(FONTS_DIR, fname)
        if fname not in downloaded:
            print(f"   • {family} {weight} {style} [{subset}] -> {fname}")
            data = _fetch(m_url.group(1), binary=True)
            with open(dest, "wb") as fh:
                fh.write(data)
            downloaded[fname] = len(data)

        # Rewrite the src URL to the local path (served from the site root, so
        # /fonts/<file>). `block` already contains the full "@font-face { ... }"
        # rule; keep font-display, unicode-range, etc. as-is.
        local_block = block.replace(m_url.group(1), f"/fonts/{fname}").strip()
        out_blocks.append(f"/* {subset} */\n{local_block}")
        kept += 1

    if not kept:
        print("❌ No matching font-face blocks found - did the Google CSS format "
              "change? Aborting without writing fonts.css.")
        sys.exit(1)

    header = ("/* Self-hosted web fonts. Generated by fetch_fonts.py - do not\n"
              "   edit by hand; re-run the script to regenerate. */\n")
    with open(OUTPUT_CSS, "w", encoding="utf-8") as fh:
        fh.write(header + "\n".join(out_blocks) + "\n")

    total_kb = sum(downloaded.values()) / 1024
    print(f"✅ Vendored {len(downloaded)} font files ({total_kb:.0f} KB) into "
          f"{FONTS_DIR}/ and wrote {OUTPUT_CSS}.")
    print("   Next: ensure templates/base.html links /fonts.css instead of "
          "Google, and that .gitignore tracks static/fonts/ + static/fonts.css.")


if __name__ == "__main__":
    main()
